version: 2

project_name: dependency-track-postprocessupdater

before:
  hooks:
    - go mod tidy

builds:
  - id: dependency-track-postprocessupdater
    main: ./main.go
    binary: dependency-track-postprocessupdater
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X dependency-track-postprocessupdater/internal/version.version={{ .Version }}
      - -X dependency-track-postprocessupdater/internal/version.commit={{ .Commit }}
      - -X dependency-track-postprocessupdater/internal/version.date={{ .Date }}

dockers:
  - id: image-amd64
    ids:
      - dependency-track-postprocessupdater
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:{{ .Version }}-amd64
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:latest-amd64

  - id: image-arm64
    ids:
      - dependency-track-postprocessupdater
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:{{ .Version }}-arm64
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:latest-arm64

docker_manifests:
  - name_template: ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:{{ .Version }}
    image_templates:
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:{{ .Version }}-amd64
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:{{ .Version }}-arm64

  - name_template: ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:latest
    image_templates:
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:latest-amd64
      - ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}/dependency-track-postprocessupdater:latest-arm64

release:
  github:
    owner: "{{ tolower .Env.GITHUB_REPOSITORY_OWNER }}"
    name: dependency-track-postprocessupdater